apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "springcity.fullname" . }}-config
  labels:
    {{- include "springcity.labels" . | nindent 4 }}
data:
  {{- range .Values.appConfig.env }}
  {{ .name }}: {{ .value | quote }}
  {{- end }} 