services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: city_api
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d