# Fichier values.yaml corrigé et complet pour city-api

replicaCount: 1

image:
  repository: axelfrache/city-api
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 32080

management:
  port: 2022

probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

# Désactivez l'ingress car nous n'en avons pas besoin pour le moment
ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

appConfig:
  env:
    - name: CITY_API_ADDR
      value: "0.0.0.0"
    - name: CITY_API_PORT
      value: "8080"
    - name: CITY_API_MANAGEMENT_PORT
      value: "2022"
    - name: CITY_API_DB_URL
      value: "db-service:5432/city_api"
    - name: CITY_API_DB_USER
      value: "user"
    - name: CITY_API_DB_PWD
      value: "password"

  persistence:
    enabled: false

  logging:
    level: INFO
