image:
  repository: axelfrache/city-api
  tag: main
  pullPolicy: Always

replicaCount: 1

appConfig:
  env:
    - name: CITY_API_ADDR
      value: "0.0.0.0"
    - name: CITY_API_PORT
      value: "8080"
    - name: CITY_API_MANAGEMENT_PORT
      value: "2022"
    - name: CITY_API_DB_URL
      value: "db-service:5432/city_api"
    - name: CITY_API_DB_USER
      value: "user"
    - name: CITY_API_DB_PWD
      value: "password"
    - name: SPRING_PROFILES_ACTIVE
      value: "prod"

postgres:
  enabled: true
  storage: 1Gi

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: springcity.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false

prometheus:
  scrape: true
