name: Kotlin Linter

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Run ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          fail_on_error: true
          ktlint_version: 1.0.1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run ktlint check
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.2.1/ktlint
          chmod a+x ktlint
          ./ktlint "src/**/*.kt" --reporter=checkstyle > ktlint-report.xml || true

      - name: Upload ktlint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ktlint-report
          path: ktlint-report.xml
          retention-days: 30

      - name: Check ktlint results
        run: |
          if [ -s ktlint-report.xml ]; then
            echo "Des erreurs de style ont été trouvées. Veuillez consulter le rapport ktlint."
            cat ktlint-report.xml
            exit 1
          fi 